### ISSUE TITLE
[Bug] 异常段错误退出

### ISSUE THREAD

**Issue by elysia-best** [LingmoOS/lingmo-filemanager#3]
报错信息如下：

```
Application: lingmo-filemanager (lingmo-filemanager), signal: Segmentation fault

           PID: 1200 (lingmo-filemana)
           UID: 1000 (elysia)
           GID: 1000 (elysia)
        Signal: 11 (SEGV)
     Timestamp: Mon 2024-03-11 10:11:56 CST (7s ago)
  Command Line: /usr/bin/lingmo-filemanager --desktop
    Executable: /usr/bin/lingmo-filemanager
 Control Group: /user.slice/user-1000.slice/session-3.scope
          Unit: session-3.scope
         Slice: user-1000.slice
       Session: 3
     Owner UID: 1000 (elysia)
       Boot ID: a4e209fdab6c4f83b99546b1a9641394
    Machine ID: 723056bc717442099810624686c3829e
      Hostname: elysiaPC
       Storage: /var/lib/systemd/coredump/core.lingmo-filemana.1000.a4e209fdab6c4f83b99546b1a9641394.1200.1710123116000000.zst (present)
  Size on Disk: 47.3M
       Message: Process 1200 (lingmo-filemana) of user 1000 dumped core.
                
                Module libsystemd.so.0 from deb systemd-255.4-1.amd64
                Module libzstd.so.1 from deb libzstd-1.5.5+dfsg2-2.amd64
                Module libudev.so.1 from deb systemd-255.4-1.amd64
                Stack trace of thread 1200:
                #0  0x00007f31374a816c n/a (libc.so.6 + 0x8a16c)
                #1  0x00007f313745a472 raise (libc.so.6 + 0x3c472)
                #2  0x00007f3138ec7b56 _ZN6KCrash19defaultCrashHandlerEi (libKF5Crash.so.5 + 0x5b56)
                #3  0x00007f313745a510 n/a (libc.so.6 + 0x3c510)
                #4  0x00007f3139c4e2e2 _ZN17QQuickItemPrivate14addToDirtyListEv (libQt5Quick.so.5 + 0x24e2e2)
                #5  0x00007f3139c52cee _ZN17QQuickItemPrivate5dirtyENS_9DirtyTypeE (libQt5Quick.so.5 + 0x252cee)
                #6  0x00007f3139c5d219 _ZN10QQuickItem13setParentItemEPS_ (libQt5Quick.so.5 + 0x25d219)
                #7  0x00007f3139c5d764 _ZN10QQuickItemD1Ev (libQt5Quick.so.5 + 0x25d764)
                #8  0x00007f3139de41d9 n/a (libQt5Quick.so.5 + 0x3e41d9)
                #9  0x00007f3137cf970b _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x2f970b)
                #10 0x00007f3138962f32 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x162f32)
                #11 0x00007f3137ccc748 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2cc748)
                #12 0x00007f3137ccfe51 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5 + 0x2cfe51)
                #13 0x00007f3137d28697 n/a (libQt5Core.so.5 + 0x328697)
                #14 0x00007f3135f111f4 n/a (libglib-2.0.so.0 + 0x571f4)
                #15 0x00007f3135f14317 n/a (libglib-2.0.so.0 + 0x5a317)
                #16 0x00007f3135f14930 g_main_context_iteration (libglib-2.0.so.0 + 0x5a930)
                #17 0x00007f3137d27d4a _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x327d4a)
                #18 0x00007f3137ccb0fb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2cb0fb)
                #19 0x00007f3137cd38a4 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2d38a4)
                #20 0x0000555cff01e43b n/a (lingmo-filemanager + 0x2643b)
                #21 0x00007f31374456ca n/a (libc.so.6 + 0x276ca)
                #22 0x00007f3137445785 __libc_start_main (libc.so.6 + 0x27785)
                #23 0x0000555cff01f391 n/a (lingmo-filemanager + 0x27391)
                
                Stack trace of thread 1219:
                #0  0x00007f3137515b3c read (libc.so.6 + 0xf7b3c)
                #1  0x00007f3135f69f3f n/a (libglib-2.0.so.0 + 0xaff3f)
                #2  0x00007f3135f13c9c n/a (libglib-2.0.so.0 + 0x59c9c)
                #3  0x00007f3135f1422b n/a (libglib-2.0.so.0 + 0x5a22b)
                #4  0x00007f3135f14930 g_main_context_iteration (libglib-2.0.so.0 + 0x5a930)
                #5  0x00007f3137d27d66 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x327d66)
                #6  0x00007f3137ccb0fb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2cb0fb)
                #7  0x00007f3137ad9c52 _ZN7QThread4execEv (libQt5Core.so.5 + 0xd9c52)
                #8  0x00007f3138f5c7ab n/a (libQt5DBus.so.5 + 0x177ab)
                #9  0x00007f3137adaeb1 n/a (libQt5Core.so.5 + 0xdaeb1)
                #10 0x00007f31374a645c n/a (libc.so.6 + 0x8845c)
                #11 0x00007f3137526bbc n/a (libc.so.6 + 0x108bbc)
                
                Stack trace of thread 1318:
                #0  0x00007f31374a31c6 n/a (libc.so.6 + 0x851c6)
                #1  0x00007f31374a5888 pthread_cond_wait (libc.so.6 + 0x87888)
                #2  0x00007f3129f1992d n/a (iris_dri.so + 0x11992d)
                #3  0x00007f3129ef970b n/a (iris_dri.so + 0xf970b)
                #4  0x00007f3129f1985b n/a (iris_dri.so + 0x11985b)
                #5  0x00007f31374a645c n/a (libc.so.6 + 0x8845c)
                #6  0x00007f3137526bbc n/a (libc.so.6 + 0x108bbc)
                
                Stack trace of thread 1231:
                #0  0x00007f31374a31c6 n/a (libc.so.6 + 0x851c6)
                #1  0x00007f31374a5888 pthread_cond_wait (libc.so.6 + 0x87888)
                #2  0x00007f3129f1992d n/a (iris_dri.so + 0x11992d)
                #3  0x00007f3129ef970b n/a (iris_dri.so + 0xf970b)
                #4  0x00007f3129f1985b n/a (iris_dri.so + 0x11985b)
                #5  0x00007f31374a645c n/a (libc.so.6 + 0x8845c)
                #6  0x00007f3137526bbc n/a (libc.so.6 + 0x108bbc)
                
                Stack trace of thread 1256:
                #0  0x00007f3137519abf __poll (libc.so.6 + 0xfbabf)
                #1  0x00007f3135f14277 n/a (libglib-2.0.so.0 + 0x5a277)
                #2  0x00007f3135f14930 g_main_context_iteration (libglib-2.0.so.0 + 0x5a930)
                #3  0x00007f3137d27d66 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x327d66)
                #4  0x00007f3137ccb0fb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2cb0fb)
                #5  0x00007f3137ad9c52 _ZN7QThread4execEv (libQt5Core.so.5 + 0xd9c52)
                #6  0x00007f3139732759 n/a (libQt5Qml.so.5 + 0x332759)
                #7  0x00007f3137adaeb1 n/a (libQt5Core.so.5 + 0xdaeb1)
                #8  0x00007f31374a645c n/a (libc.so.6 + 0x8845c)
                #9  0x00007f3137526bbc n/a (libc.so.6 + 0x108bbc)
                
                Stack trace of thread 1319:
                #0  0x00007f31374a31c6 n/a (libc.so.6 + 0x851c6)
                #1  0x00007f31374a5888 pthread_cond_wait (libc.so.6 + 0x87888)
                #2  0x00007f3129f1992d n/a (iris_dri.so + 0x11992d)
                #3  0x00007f3129ef970b n/a (iris_dri.so + 0xf970b)
                #4  0x00007f3129f1985b n/a (iris_dri.so + 0x11985b)
                #5  0x00007f31374a645c n/a (libc.so.6 + 0x8845c)
                #6  0x00007f3137526bbc n/a (libc.so.6 + 0x108bbc)
                
                Stack trace of thread 1218:
                #0  0x00007f3137519abf __poll (libc.so.6 + 0xfbabf)
                #1  0x00007f3136d81d12 n/a (libxcb.so.1 + 0xcd12)
                #2  0x00007f3136d8407a xcb_wait_for_event (libxcb.so.1 + 0xf07a)
                #3  0x00007f3132a49098 n/a (libQt5XcbQpa.so.5 + 0x6e098)
                #4  0x00007f3137adaeb1 n/a (libQt5Core.so.5 + 0xdaeb1)
                #5  0x00007f31374a645c n/a (libc.so.6 + 0x8845c)
                #6  0x00007f3137526bbc n/a (libc.so.6 + 0x108bbc)
                
                Stack trace of thread 3707:
                #0  0x00007f313751c3b1 pselect (libc.so.6 + 0xfe3b1)
                #1  0x00007f3136224a8f n/a (libusbmuxd-2.0.so.6 + 0x2a8f)
                #2  0x00007f3136225d3b n/a (libusbmuxd-2.0.so.6 + 0x3d3b)
                #3  0x00007f31374a645c n/a (libc.so.6 + 0x8845c)
                #4  0x00007f3137526bbc n/a (libc.so.6 + 0x108bbc)
                
                Stack trace of thread 1230:
                #0  0x00007f31374a31c6 n/a (libc.so.6 + 0x851c6)
                #1  0x00007f31374a5888 pthread_cond_wait (libc.so.6 + 0x87888)
                #2  0x00007f3129f1992d n/a (iris_dri.so + 0x11992d)
                #3  0x00007f3129ef970b n/a (iris_dri.so + 0xf970b)
                #4  0x00007f3129f1985b n/a (iris_dri.so + 0x11985b)
                #5  0x00007f31374a645c n/a (libc.so.6 + 0x8845c)
                #6  0x00007f3137526bbc n/a (libc.so.6 + 0x108bbc)
                
                Stack trace of thread 1320:
                #0  0x00007f31374a31c6 n/a (libc.so.6 + 0x851c6)
                #1  0x00007f31374a5888 pthread_cond_wait (libc.so.6 + 0x87888)
                #2  0x00007f3137ae0cab _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xe0cab)
                #3  0x00007f3139c0b7fc n/a (libQt5Quick.so.5 + 0x20b7fc)
                #4  0x00007f3139c0dc39 n/a (libQt5Quick.so.5 + 0x20dc39)
                #5  0x00007f3137adaeb1 n/a (libQt5Core.so.5 + 0xdaeb1)
                #6  0x00007f31374a645c n/a (libc.so.6 + 0x8845c)
                #7  0x00007f3137526bbc n/a (libc.so.6 + 0x108bbc)
                ELF object binary architecture: AMD x86-64

[New LWP 1200]
[New LWP 1219]
[New LWP 1318]
[New LWP 1231]
[New LWP 1256]
[New LWP 1319]
[New LWP 1218]
[New LWP 3707]
[New LWP 1230]
[New LWP 1320]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/lingmo-filemanager --desktop'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f31374a816c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
[Current thread is 1 (Thread 0x7f3132f8b1c0 (LWP 1200))]
[Current thread is 1 (Thread 0x7f3132f8b1c0 (LWP 1200))]

Thread 10 (Thread 0x7f30fb7fe6c0 (LWP 1320)):
#0  0x00007f31374a31c6 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f31374a5888 in pthread_cond_wait () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f3137ae0cab in QWaitCondition::wait(QMutex*, QDeadlineTimer) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007f3139c0b7fc in ?? () from /lib/x86_64-linux-gnu/libQt5Quick.so.5
#4  0x00007f3139c0dc39 in ?? () from /lib/x86_64-linux-gnu/libQt5Quick.so.5
#5  0x00007f3137adaeb1 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f31374a645c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007f3137526bbc in ?? () from /lib/x86_64-linux-gnu/libc.so.6

Thread 9 (Thread 0x7f311c7ff6c0 (LWP 1230)):
#0  0x00007f31374a31c6 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f31374a5888 in pthread_cond_wait () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f3129f1992d in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#3  0x00007f3129ef970b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x00007f3129f1985b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#5  0x00007f31374a645c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007f3137526bbc in ?? () from /lib/x86_64-linux-gnu/libc.so.6

Thread 8 (Thread 0x7f31017fa6c0 (LWP 3707)):
#0  0x00007f313751c3b1 in pselect () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f3136224a8f in ?? () from /lib/x86_64-linux-gnu/libusbmuxd-2.0.so.6
#2  0x00007f3136225d3b in ?? () from /lib/x86_64-linux-gnu/libusbmuxd-2.0.so.6
#3  0x00007f31374a645c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f3137526bbc in ?? () from /lib/x86_64-linux-gnu/libc.so.6

Thread 7 (Thread 0x7f31325ff6c0 (LWP 1218)):
#0  0x00007f3137519abf in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f3136d81d12 in ?? () from /lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f3136d8407a in xcb_wait_for_event () from /lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f3132a49098 in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f3137adaeb1 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f31374a645c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007f3137526bbc in ?? () from /lib/x86_64-linux-gnu/libc.so.6

Thread 6 (Thread 0x7f30fbfff6c0 (LWP 1319)):
#0  0x00007f31374a31c6 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f31374a5888 in pthread_cond_wait () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f3129f1992d in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#3  0x00007f3129ef970b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x00007f3129f1985b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#5  0x00007f31374a645c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007f3137526bbc in ?? () from /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7f311b7fd6c0 (LWP 1256)):
#0  0x00007f3137519abf in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f3135f14277 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f3135f14930 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f3137d27d66 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f3137ccb0fb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f3137ad9c52 in QThread::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f3139732759 in ?? () from /lib/x86_64-linux-gnu/libQt5Qml.so.5
#7  0x00007f3137adaeb1 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f31374a645c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#9  0x00007f3137526bbc in ?? () from /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7f311bffe6c0 (LWP 1231)):
#0  0x00007f31374a31c6 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f31374a5888 in pthread_cond_wait () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f3129f1992d in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#3  0x00007f3129ef970b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x00007f3129f1985b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#5  0x00007f31374a645c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007f3137526bbc in ?? () from /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7f3100ff96c0 (LWP 1318)):
#0  0x00007f31374a31c6 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f31374a5888 in pthread_cond_wait () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f3129f1992d in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#3  0x00007f3129ef970b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x00007f3129f1985b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#5  0x00007f31374a645c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007f3137526bbc in ?? () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7f3131be16c0 (LWP 1219)):
#0  0x00007f3137515b3c in read () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f3135f69f3f in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f3135f13c9c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f3135f1422b in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f3135f14930 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f3137d27d66 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f3137ccb0fb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f3137ad9c52 in QThread::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f3138f5c7ab in ?? () from /lib/x86_64-linux-gnu/libQt5DBus.so.5
#9  0x00007f3137adaeb1 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007f31374a645c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#11 0x00007f3137526bbc in ?? () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7f3132f8b1c0 (LWP 1200)):
[KCrash Handler]
#4  0x00007f3139c4e2e2 in QQuickItemPrivate::addToDirtyList() () from /lib/x86_64-linux-gnu/libQt5Quick.so.5
#5  0x00007f3139c52cee in QQuickItemPrivate::dirty(QQuickItemPrivate::DirtyType) () from /lib/x86_64-linux-gnu/libQt5Quick.so.5
#6  0x00007f3139c5d219 in QQuickItem::setParentItem(QQuickItem*) () from /lib/x86_64-linux-gnu/libQt5Quick.so.5
#7  0x00007f3139c5d764 in QQuickItem::~QQuickItem() () from /lib/x86_64-linux-gnu/libQt5Quick.so.5
#8  0x00007f3139de41d9 in ?? () from /lib/x86_64-linux-gnu/libQt5Quick.so.5
#9  0x00007f3137cf970b in QObject::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007f3138962f32 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007f3137ccc748 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007f3137ccfe51 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007f3137d28697 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007f3135f111f4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007f3135f14317 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f3135f14930 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007f3137d27d4a in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007f3137ccb0fb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007f3137cd38a4 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x0000555cff01e43b in ?? ()
#21 0x00007f31374456ca in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#22 0x00007f3137445785 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#23 0x0000555cff01f391 in ?? ()
```

暂时只在我的机器上出现。

**Comment by everything411** [comment]
reproduce on Lingmo OS 2.0
```
Core was generated by `/bin/lingmo-filemanager --desktop'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f376d24e122 in QQuickItemPrivate::addToDirtyList() () from /lib/x86_64-linux-gnu/libQt5Quick.so.5
[Current thread is 1 (Thread 0x7f3769186000 (LWP 2124))]
(gdb) bt
#0  0x00007f376d24e122 in QQuickItemPrivate::addToDirtyList() () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#1  0x00007f376d252b1e in QQuickItemPrivate::dirty(QQuickItemPrivate::DirtyType) ()
    at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#2  0x00007f376d25d029 in QQuickItem::setParentItem(QQuickItem*) () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#3  0x00007f376d25d574 in QQuickItem::~QQuickItem() () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#4  0x00007f376d3e4299 in ??? () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#5  0x00007f376b50bd09 in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f376c163092 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007f376b4de398 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f376b4e1899 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f376b53bb57 in ??? () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007f376990c7df in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007f376990ea17 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007f376990f180 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007f376b53b1ed in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007f376b4dcd02 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007f376b4e5722 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x000055b2fc45346b in ??? ()
#17 0x00007f376ac3edba in __libc_start_call_main
    (main=main@entry=0x55b2fc451b40, argc=argc@entry=2, argv=argv@entry=0x7ffe9b9e5c68)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#18 0x00007f376ac3ee75 in __libc_start_main_impl
--Type <RET> for more, q to quit, c to continue without paging--
    (main=0x55b2fc451b40, argc=2, argv=0x7ffe9b9e5c68, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe9b9e5c58) at ../csu/libc-start.c:360
#19 0x000055b2fc4543c1 in ??? ()
```
